name: First workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello, Switzeland!"
      - name: Run a multi-line script
        run: |
          echo "Sagar is wokring on new Project !!!!",
          echo "Richa got a lovely new job !!!!"
